# Generated by Django 5.2.15 on 2026-06-13 04:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_competency_learningarea_learningoutcome_and_more'),
        ('accounts', '0002_auditlog'),
        ('tenancy', '0002_enable_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='tenancy.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TeacherProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_number', models.CharField(max_length=40)),
                ('tsc_number', models.CharField(blank=True, max_length=40)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('employment_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('on_leave', 'On leave'), ('inactive', 'Inactive')], default='active', max_length=16)),
                ('membership', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='teacher_profile', to='accounts.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_profiles', to='tenancy.school')),
            ],
            options={
                'ordering': ['employee_number'],
            },
        ),
        migrations.CreateModel(
            name='StaffAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('subject_teacher', 'Subject teacher'), ('class_teacher', 'Class teacher'), ('department_head', 'Department head')], max_length=24)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('weekly_lessons', models.PositiveSmallIntegerField(default=0)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='staff.department')),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='academics.grade')),
                ('learning_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='academics.learningarea')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='tenancy.school')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_assignments', to='academics.stream')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='staff.teacherprofile')),
            ],
            options={
                'ordering': ['teacher__employee_number', 'role', '-start_date'],
            },
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_departments', to='staff.teacherprofile'),
        ),
        migrations.AddIndex(
            model_name='teacherprofile',
            index=models.Index(fields=['school', 'status', 'employee_number'], name='staff_teach_school__00e1d4_idx'),
        ),
        migrations.AddConstraint(
            model_name='teacherprofile',
            constraint=models.UniqueConstraint(fields=('school', 'employee_number'), name='unique_teacher_employee_number_per_school'),
        ),
        migrations.AddConstraint(
            model_name='teacherprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('tsc_number', ''), _negated=True), fields=('school', 'tsc_number'), name='unique_teacher_tsc_number_per_school'),
        ),
        migrations.AddIndex(
            model_name='staffassignment',
            index=models.Index(fields=['school', 'role', 'start_date'], name='staff_staff_school__37d744_idx'),
        ),
        migrations.AddIndex(
            model_name='staffassignment',
            index=models.Index(fields=['school', 'teacher', 'end_date'], name='staff_staff_school__a460c2_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['school', 'is_active', 'name'], name='staff_depar_school__556cf3_idx'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_department_code_per_school'),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_department_name_per_school'),
        ),
    ]
