# Generated by Django 5.2.15 on 2026-06-13 04:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auditlog'),
        ('tenancy', '0002_enable_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(max_length=32)),
                ('national_id', models.CharField(blank=True, max_length=40)),
                ('postal_address', models.TextField(blank=True)),
                ('membership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_profiles', to='accounts.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardians', to='tenancy.school')),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Learner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_number', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=80)),
                ('middle_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('not_stated', 'Prefer not to say')], max_length=16)),
                ('admission_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('transferred', 'Transferred'), ('graduated', 'Graduated')], default='active', max_length=16)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learners', to='tenancy.school')),
            ],
            options={
                'ordering': ['last_name', 'first_name', 'admission_number'],
            },
        ),
        migrations.CreateModel(
            name='LearnerGuardian',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('relationship', models.CharField(choices=[('mother', 'Mother'), ('father', 'Father'), ('guardian', 'Guardian'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=16)),
                ('is_primary', models.BooleanField(default=False)),
                ('receives_communication', models.BooleanField(default=True)),
                ('authorized_pickup', models.BooleanField(default=False)),
                ('guardian', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learner_links', to='learners.guardian')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardian_links', to='learners.learner')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learner_guardian_links', to='tenancy.school')),
            ],
            options={
                'ordering': ['-is_primary', 'guardian__last_name'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('blood_group', models.CharField(blank=True, max_length=8)),
                ('allergies', models.TextField(blank=True)),
                ('conditions', models.TextField(blank=True)),
                ('medication', models.TextField(blank=True)),
                ('emergency_notes', models.TextField(blank=True)),
                ('learner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='medical_record', to='learners.learner')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='tenancy.school')),
            ],
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['school', 'last_name', 'first_name'], name='learners_gu_school__235de7_idx'),
        ),
        migrations.AddIndex(
            model_name='guardian',
            index=models.Index(fields=['school', 'phone_number'], name='learners_gu_school__9e1426_idx'),
        ),
        migrations.AddConstraint(
            model_name='guardian',
            constraint=models.UniqueConstraint(condition=models.Q(('membership__isnull', False)), fields=('school', 'membership'), name='unique_guardian_membership_per_school'),
        ),
        migrations.AddConstraint(
            model_name='guardian',
            constraint=models.UniqueConstraint(condition=models.Q(('email', ''), _negated=True), fields=('school', 'email'), name='unique_guardian_email_per_school'),
        ),
        migrations.AddIndex(
            model_name='learner',
            index=models.Index(fields=['school', 'status', 'last_name'], name='learners_le_school__a69c9f_idx'),
        ),
        migrations.AddIndex(
            model_name='learner',
            index=models.Index(fields=['school', 'admission_date'], name='learners_le_school__4ae3c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='learner',
            constraint=models.UniqueConstraint(fields=('school', 'admission_number'), name='unique_learner_admission_number_per_school'),
        ),
        migrations.AddIndex(
            model_name='learnerguardian',
            index=models.Index(fields=['school', 'learner', 'is_primary'], name='learners_le_school__2d23bc_idx'),
        ),
        migrations.AddIndex(
            model_name='learnerguardian',
            index=models.Index(fields=['school', 'guardian'], name='learners_le_school__31bac5_idx'),
        ),
        migrations.AddConstraint(
            model_name='learnerguardian',
            constraint=models.UniqueConstraint(fields=('school', 'learner', 'guardian'), name='unique_learner_guardian_link'),
        ),
        migrations.AddConstraint(
            model_name='learnerguardian',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('school', 'learner'), name='one_primary_guardian_per_learner'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['school', 'learner'], name='learners_me_school__9006b8_idx'),
        ),
    ]
