# Generated by Django 5.2.15 on 2026-06-13 04:12

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_competency_learningarea_learningoutcome_and_more'),
        ('learners', '0001_initial'),
        ('tenancy', '0002_enable_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=80)),
                ('middle_name', models.CharField(blank=True, max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('other', 'Other'), ('not_stated', 'Prefer not to say')], max_length=16)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('reviewing', 'Reviewing'), ('admitted', 'Admitted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn')], default='submitted', max_length=16)),
                ('submitted_at', models.DateField()),
                ('admitted_at', models.DateTimeField(blank=True, null=True)),
                ('desired_grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_applications', to='academics.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_applications', to='tenancy.school')),
            ],
            options={
                'ordering': ['-submitted_at', 'last_name', 'first_name'],
                'indexes': [models.Index(fields=['school', 'status', 'submitted_at'], name='learners_ad_school__87ea24_idx')],
            },
        ),
        migrations.CreateModel(
            name='AdmissionSequence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField()),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admission_sequences', to='tenancy.school')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('school', 'year'), name='unique_admission_sequence_per_school_year')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('transferred', 'Transferred'), ('withdrawn', 'Withdrawn')], default='active', max_length=16)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.academicyear')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.grade')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='learners.learner')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='tenancy.school')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.stream')),
            ],
            options={
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['school', 'academic_year', 'grade', 'stream'], name='learners_en_school__a09074_idx'), models.Index(fields=['school', 'status', 'start_date'], name='learners_en_school__220f78_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('school', 'learner'), name='one_active_enrollment_per_learner')],
            },
        ),
    ]
