# Generated by Django 5.2.15 on 2026-06-13 04:13

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learners', '0002_admissionapplication_admissionsequence_enrollment'),
        ('tenancy', '0002_enable_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination_school_name', models.CharField(max_length=200)),
                ('transfer_date', models.DateField()),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('export_reference', models.CharField(blank=True, max_length=80)),
                ('exported_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_records', to='learners.enrollment')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfer_records', to='learners.learner')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_records', to='tenancy.school')),
            ],
            options={
                'ordering': ['-transfer_date', '-created_at'],
                'indexes': [models.Index(fields=['school', 'status', 'transfer_date'], name='learners_tr_school__284153_idx'), models.Index(fields=['school', 'learner'], name='learners_tr_school__181f83_idx')],
            },
        ),
    ]
