# Generated by Django 5.2.15 on 2026-06-13 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditlog'),
        ('learners', '0003_transferrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='membership',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learner_profile', to='accounts.membership'),
        ),
    ]
