# Generated by Django 5.2.15 on 2026-06-13 12:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_competency_learningarea_learningoutcome_and_more'),
        ('staff', '0001_initial'),
        ('tenancy', '0003_milestone_2_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='tenancy.school')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Timetable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetables', to='academics.academicyear')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_timetables', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='tenancy.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetables', to='academics.term')),
            ],
            options={
                'ordering': ['-academic_year__start_date', 'term__sequence', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TimetablePeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('sequence', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=80)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_break', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_periods', to='tenancy.school')),
            ],
            options={
                'ordering': ['weekday', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='academics.learningarea')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='timetabling.room')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='tenancy.school')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='academics.stream')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='timetable_entries', to='staff.teacherprofile')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='timetabling.timetable')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='timetabling.timetableperiod')),
            ],
            options={
                'ordering': ['period__weekday', 'period__sequence', 'stream__grade__order'],
            },
        ),
        migrations.AddIndex(
            model_name='room',
            index=models.Index(fields=['school', 'is_active', 'code'], name='timetabling_school__cf4e44_idx'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_room_code_per_school'),
        ),
        migrations.AddIndex(
            model_name='timetable',
            index=models.Index(fields=['school', 'status', 'term'], name='timetabling_school__f16573_idx'),
        ),
        migrations.AddConstraint(
            model_name='timetable',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'term', 'name'), name='unique_named_timetable_per_term'),
        ),
        migrations.AddIndex(
            model_name='timetableperiod',
            index=models.Index(fields=['school', 'weekday', 'sequence'], name='timetabling_school__37a76b_idx'),
        ),
        migrations.AddConstraint(
            model_name='timetableperiod',
            constraint=models.UniqueConstraint(fields=('school', 'weekday', 'sequence'), name='unique_timetable_period_sequence'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['school', 'timetable', 'period'], name='timetabling_school__ffaf4c_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['school', 'teacher', 'period'], name='timetabling_school__7ba44f_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['school', 'stream', 'period'], name='timetabling_school__ba3f81_idx'),
        ),
        migrations.AddIndex(
            model_name='timetableentry',
            index=models.Index(fields=['school', 'room', 'period'], name='timetabling_school__8dd2f3_idx'),
        ),
    ]
