# Generated by Django 5.2.15 on 2026-06-13 17:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('learners', '0004_learner_membership'),
        ('tenancy', '0007_milestone_6_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DisciplineRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('positive', 'Positive conduct'), ('concern', 'Behaviour concern'), ('counselling', 'Counselling')], max_length=16)),
                ('title', models.CharField(max_length=180)),
                ('details', models.TextField()),
                ('action_taken', models.TextField(blank=True)),
                ('is_confidential', models.BooleanField(default=False)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='learners.learner')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.school')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['school', 'learner', 'category'], name='wellbeing_d_school__5146f2_idx')],
            },
        ),
    ]
