# Generated by Django 5.2.15 on 2026-06-13 03:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_enable_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('active', 'Active'), ('closed', 'Closed')], default='planned', max_length=16)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_years', to='tenancy.school')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32)),
                ('name', models.CharField(max_length=80)),
                ('education_level', models.CharField(choices=[('pre_primary', 'Pre-primary'), ('primary', 'Primary'), ('junior_school', 'Junior school'), ('senior_school', 'Senior school')], max_length=24)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grades', to='tenancy.school')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32)),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='streams', to='academics.grade')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streams', to='tenancy.school')),
            ],
            options={
                'ordering': ['grade__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=40)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='academics.academicyear')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='terms', to='tenancy.school')),
            ],
            options={
                'ordering': ['academic_year', 'sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='academicyear',
            index=models.Index(fields=['school', 'status', 'start_date'], name='academics_a_school__2b3fab_idx'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_academic_year_name_per_school'),
        ),
        migrations.AddIndex(
            model_name='grade',
            index=models.Index(fields=['school', 'is_active', 'order'], name='academics_g_school__8a9f76_idx'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_grade_code_per_school'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_grade_name_per_school'),
        ),
        migrations.AddIndex(
            model_name='stream',
            index=models.Index(fields=['school', 'is_active'], name='academics_s_school__b6e6b0_idx'),
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('school', 'grade', 'code'), name='unique_stream_code_per_grade'),
        ),
        migrations.AddConstraint(
            model_name='stream',
            constraint=models.UniqueConstraint(fields=('school', 'grade', 'name'), name='unique_stream_name_per_grade'),
        ),
        migrations.AddIndex(
            model_name='term',
            index=models.Index(fields=['school', 'start_date', 'end_date'], name='academics_t_school__585ef8_idx'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'sequence'), name='unique_term_sequence_per_academic_year'),
        ),
        migrations.AddConstraint(
            model_name='term',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'name'), name='unique_term_name_per_academic_year'),
        ),
    ]
