# Generated by Django 5.2.15 on 2026-06-13 03:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('tenancy', '0002_enable_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to='tenancy.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LearningArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=40)),
                ('name', models.CharField(max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_areas', to='tenancy.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LearningOutcome',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=80)),
                ('description', models.TextField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_outcomes', to='tenancy.school')),
            ],
            options={
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='OutcomeCompetency',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_links', to='academics.competency')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_links', to='academics.learningoutcome')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcome_competencies', to='tenancy.school')),
            ],
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='competencies',
            field=models.ManyToManyField(related_name='learning_outcomes', through='academics.OutcomeCompetency', to='academics.competency'),
        ),
        migrations.CreateModel(
            name='Strand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField()),
                ('name', models.CharField(max_length=160)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strands', to='academics.grade')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='strands', to='academics.learningarea')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='strands', to='tenancy.school')),
            ],
            options={
                'ordering': ['learning_area__name', 'grade__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SubStrand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=60)),
                ('name', models.CharField(max_length=180)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_strands', to='tenancy.school')),
                ('strand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sub_strands', to='academics.strand')),
            ],
            options={
                'ordering': ['strand__name', 'name'],
            },
        ),
        migrations.AddField(
            model_name='learningoutcome',
            name='sub_strand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learning_outcomes', to='academics.substrand'),
        ),
        migrations.AddIndex(
            model_name='competency',
            index=models.Index(fields=['school', 'is_active', 'name'], name='academics_c_school__0b6cf0_idx'),
        ),
        migrations.AddConstraint(
            model_name='competency',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_competency_code_per_school'),
        ),
        migrations.AddConstraint(
            model_name='competency',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_competency_name_per_school'),
        ),
        migrations.AddIndex(
            model_name='learningarea',
            index=models.Index(fields=['school', 'is_active', 'name'], name='academics_l_school__acb937_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningarea',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_learning_area_code_per_school'),
        ),
        migrations.AddConstraint(
            model_name='learningarea',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_learning_area_name_per_school'),
        ),
        migrations.AddIndex(
            model_name='outcomecompetency',
            index=models.Index(fields=['school', 'outcome'], name='academics_o_school__3d08c8_idx'),
        ),
        migrations.AddIndex(
            model_name='outcomecompetency',
            index=models.Index(fields=['school', 'competency'], name='academics_o_school__c4de68_idx'),
        ),
        migrations.AddConstraint(
            model_name='outcomecompetency',
            constraint=models.UniqueConstraint(fields=('school', 'outcome', 'competency'), name='unique_outcome_competency_link'),
        ),
        migrations.AddIndex(
            model_name='strand',
            index=models.Index(fields=['school', 'learning_area', 'grade'], name='academics_s_school__d58755_idx'),
        ),
        migrations.AddConstraint(
            model_name='strand',
            constraint=models.UniqueConstraint(fields=('school', 'learning_area', 'grade', 'code'), name='unique_strand_code_per_area_grade'),
        ),
        migrations.AddIndex(
            model_name='substrand',
            index=models.Index(fields=['school', 'strand'], name='academics_s_school__25209b_idx'),
        ),
        migrations.AddConstraint(
            model_name='substrand',
            constraint=models.UniqueConstraint(fields=('school', 'strand', 'code'), name='unique_sub_strand_code_per_strand'),
        ),
        migrations.AddIndex(
            model_name='learningoutcome',
            index=models.Index(fields=['school', 'sub_strand'], name='academics_l_school__3cd1e7_idx'),
        ),
        migrations.AddConstraint(
            model_name='learningoutcome',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_learning_outcome_code_per_school'),
        ),
    ]
