# Generated by Django 5.2.15 on 2026-06-28 08:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


def seed_stream_labels(apps, schema_editor):
    Stream = apps.get_model("academics", "Stream")
    StreamLabel = apps.get_model("academics", "StreamLabel")
    seen = set()
    streams = Stream.objects.filter(is_active=True).order_by(
        "school_id",
        "grade__order",
        "grade__name",
        "name",
        "created_at",
    )
    for stream in streams:
        key = (stream.school_id, stream.name.casefold())
        if key in seen:
            continue
        seen.add(key)
        StreamLabel.objects.get_or_create(
            school_id=stream.school_id,
            name=stream.name,
            defaults={
                "code": stream.code,
                "is_active": stream.is_active,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_competency_learningarea_learningoutcome_and_more'),
        ('tenancy', '0008_milestone_7_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamLabel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=32)),
                ('name', models.CharField(max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_labels', to='tenancy.school')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['school', 'is_active', 'name'], name='academics_s_school__246074_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'code'), name='unique_stream_label_code_per_school'), models.UniqueConstraint(fields=('school', 'name'), name='unique_stream_label_name_per_school')],
            },
        ),
        migrations.RunPython(seed_stream_labels, migrations.RunPython.noop),
    ]
