# Generated by Django 5.2.15 on 2026-06-13 17:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_competency_learningarea_learningoutcome_and_more'),
        ('learners', '0004_learner_membership'),
        ('staff', '0001_initial'),
        ('tenancy', '0006_milestone_5_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('instructions', models.TextField()),
                ('due_at', models.DateTimeField()),
                ('is_published', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.learningarea')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.school')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.stream')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.teacherprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.term')),
            ],
            options={
                'ordering': ['-published_at', 'due_at'],
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('kind', models.CharField(choices=[('note', 'Note'), ('file', 'File'), ('video', 'Video')], max_length=12)),
                ('content', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='resources/%Y/%m/')),
                ('is_published', models.BooleanField(default=True)),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.learningarea')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.teacherprofile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('response', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='submissions/%Y/%m/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('feedback', models.TextField(blank=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='learning.assignment')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='learners.learner')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.school')),
            ],
        ),
        migrations.AddIndex(
            model_name='assignment',
            index=models.Index(fields=['school', 'stream', 'is_published'], name='learning_as_school__35ae4e_idx'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('school', 'assignment', 'learner'), name='unique_assignment_submission'),
        ),
    ]
