# Generated by Django 5.2.15 on 2026-06-13 14:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_competency_learningarea_learningoutcome_and_more'),
        ('learners', '0004_learner_membership'),
        ('staff', '0001_initial'),
        ('tenancy', '0004_milestone_3_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('assessment_type', models.CharField(choices=[('formative', 'Formative'), ('summative', 'Summative')], max_length=16)),
                ('assessment_date', models.DateField()),
                ('instructions', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('submitted', 'Submitted for moderation'), ('moderated', 'Moderated'), ('approved', 'Approved'), ('published', 'Published')], default='draft', max_length=16)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('moderated_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.learningarea')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='tenancy.school')),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.stream')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='staff.teacherprofile')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.term')),
            ],
            options={
                'ordering': ['-assessment_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='RatingLevel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.SlugField(max_length=16)),
                ('name', models.CharField(max_length=80)),
                ('description', models.TextField(blank=True)),
                ('rank', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rating_levels', to='tenancy.school')),
            ],
            options={
                'ordering': ['-rank', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('moderated_comment', models.TextField(blank=True)),
                ('is_complete', models.BooleanField(default=False)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='results', to='assessments.assessment')),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_results', to='learners.learner')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='tenancy.school')),
                ('overall_rating', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='overall_results', to='assessments.ratinglevel')),
            ],
            options={
                'ordering': ['learner__last_name', 'learner__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Rubric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubrics', to='academics.grade')),
                ('learning_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubrics', to='academics.learningarea')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubrics', to='tenancy.school')),
            ],
            options={
                'ordering': ['learning_area__name', 'grade__order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='assessment',
            name='rubric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='assessments.rubric'),
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveSmallIntegerField()),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubric_criteria', to='academics.learningoutcome')),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='assessments.rubric')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rubric_criteria', to='tenancy.school')),
            ],
            options={
                'ordering': ['rubric', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='CriterionRating',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.CharField(blank=True, max_length=250)),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_ratings', to='assessments.assessmentresult')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criterion_ratings', to='tenancy.school')),
                ('rating', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='criterion_ratings', to='assessments.ratinglevel')),
                ('criterion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='assessments.rubriccriterion')),
            ],
            options={
                'ordering': ['criterion__sequence'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentWorkflowEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=40)),
                ('from_status', models.CharField(max_length=16)),
                ('to_status', models.CharField(max_length=16)),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_workflow_events', to=settings.AUTH_USER_MODEL)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='workflow_events', to='assessments.assessment')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_workflow_events', to='tenancy.school')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['school', 'assessment', 'created_at'], name='assessments_school__fdf4b8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='assessment-evidence/%Y/%m/')),
                ('file_name', models.CharField(max_length=255)),
                ('content_type', models.CharField(max_length=120)),
                ('size_bytes', models.PositiveIntegerField()),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='portfolio_evidence', to='learners.learner')),
                ('outcome', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_evidence', to='academics.learningoutcome')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='assessments.assessmentresult')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_evidence', to='tenancy.school')),
            ],
            options={
                'ordering': ['-captured_at'],
                'indexes': [models.Index(fields=['school', 'learner', 'captured_at'], name='assessments_school__a363e3_idx'), models.Index(fields=['school', 'result'], name='assessments_school__6e2e37_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='ratinglevel',
            index=models.Index(fields=['school', 'is_active', 'rank'], name='assessments_school__7dba0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='ratinglevel',
            constraint=models.UniqueConstraint(fields=('school', 'code'), name='unique_rating_code_per_school'),
        ),
        migrations.AddConstraint(
            model_name='ratinglevel',
            constraint=models.UniqueConstraint(fields=('school', 'rank'), name='unique_rating_rank_per_school'),
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['school', 'assessment', 'is_complete'], name='assessments_school__0fa279_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentresult',
            index=models.Index(fields=['school', 'learner'], name='assessments_school__4a2f3d_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentresult',
            constraint=models.UniqueConstraint(fields=('school', 'assessment', 'learner'), name='unique_assessment_result_per_learner'),
        ),
        migrations.AddIndex(
            model_name='rubric',
            index=models.Index(fields=['school', 'learning_area', 'grade'], name='assessments_school__5464ea_idx'),
        ),
        migrations.AddConstraint(
            model_name='rubric',
            constraint=models.UniqueConstraint(fields=('school', 'learning_area', 'grade', 'name'), name='unique_named_rubric_per_area_grade'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['school', 'status', 'assessment_date'], name='assessments_school__656071_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['school', 'term', 'stream', 'learning_area'], name='assessments_school__617961_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessment',
            constraint=models.UniqueConstraint(fields=('school', 'term', 'stream', 'learning_area', 'title'), name='unique_named_assessment_per_class_term'),
        ),
        migrations.AddIndex(
            model_name='rubriccriterion',
            index=models.Index(fields=['school', 'rubric', 'sequence'], name='assessments_school__63c524_idx'),
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.UniqueConstraint(fields=('school', 'rubric', 'sequence'), name='unique_criterion_sequence_per_rubric'),
        ),
        migrations.AddConstraint(
            model_name='rubriccriterion',
            constraint=models.UniqueConstraint(fields=('school', 'rubric', 'outcome'), name='unique_outcome_per_rubric'),
        ),
        migrations.AddIndex(
            model_name='criterionrating',
            index=models.Index(fields=['school', 'result', 'criterion'], name='assessments_school__7075aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='criterionrating',
            constraint=models.UniqueConstraint(fields=('school', 'result', 'criterion'), name='unique_criterion_rating_per_result'),
        ),
    ]
