# Generated by Django 5.2.15 on 2026-06-13 11:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_competency_learningarea_learningoutcome_and_more'),
        ('learners', '0004_learner_membership'),
        ('staff', '0001_initial'),
        ('tenancy', '0003_milestone_2_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRegister',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attendance_date', models.DateField()),
                ('session', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon')], max_length=16)),
                ('subject_type', models.CharField(choices=[('learner', 'Learner'), ('staff', 'Staff')], max_length=16)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('completed', 'Completed')], default='draft', max_length=16)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='marked_attendance_registers', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_registers', to='tenancy.school')),
                ('stream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_registers', to='academics.stream')),
            ],
            options={
                'ordering': ['-attendance_date', 'session', 'subject_type'],
            },
        ),
        migrations.CreateModel(
            name='LearnerAttendanceEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=16)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_entries', to='learners.learner')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='learner_entries', to='attendance.attendanceregister')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.school')),
            ],
            options={
                'ordering': ['learner__last_name', 'learner__first_name'],
            },
        ),
        migrations.CreateModel(
            name='StaffAttendanceEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=16)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_entries', to='attendance.attendanceregister')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.school')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_entries', to='staff.teacherprofile')),
            ],
            options={
                'ordering': ['teacher__employee_number'],
            },
        ),
        migrations.CreateModel(
            name='AttendanceCorrection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('old_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=16)),
                ('new_status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late'), ('excused', 'Excused')], max_length=16)),
                ('old_arrival_time', models.TimeField(blank=True, null=True)),
                ('new_arrival_time', models.TimeField(blank=True, null=True)),
                ('old_note', models.CharField(blank=True, max_length=250)),
                ('new_note', models.CharField(blank=True, max_length=250)),
                ('reason', models.TextField()),
                ('corrected_at', models.DateTimeField(auto_now_add=True)),
                ('corrected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_corrections', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_corrections', to='tenancy.school')),
                ('learner_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='attendance.learnerattendanceentry')),
                ('staff_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='corrections', to='attendance.staffattendanceentry')),
            ],
            options={
                'ordering': ['-corrected_at'],
            },
        ),
        migrations.CreateModel(
            name='AbsenceAlert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_summary', models.CharField(blank=True, max_length=250)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('acknowledged', 'Acknowledged')], default='pending', max_length=16)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absence_alerts', to='tenancy.school')),
                ('learner_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='absence_alert', to='attendance.learnerattendanceentry')),
                ('staff_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='absence_alert', to='attendance.staffattendanceentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='attendanceregister',
            index=models.Index(fields=['school', 'attendance_date', 'subject_type'], name='attendance__school__257b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='attendanceregister',
            index=models.Index(fields=['school', 'status', 'attendance_date'], name='attendance__school__b5962b_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendanceregister',
            constraint=models.UniqueConstraint(condition=models.Q(('subject_type', 'learner')), fields=('school', 'attendance_date', 'session', 'stream'), name='unique_learner_attendance_register'),
        ),
        migrations.AddConstraint(
            model_name='attendanceregister',
            constraint=models.UniqueConstraint(condition=models.Q(('subject_type', 'staff')), fields=('school', 'attendance_date', 'session'), name='unique_staff_attendance_register'),
        ),
        migrations.AddIndex(
            model_name='learnerattendanceentry',
            index=models.Index(fields=['school', 'learner', 'status'], name='attendance__school__4371fc_idx'),
        ),
        migrations.AddIndex(
            model_name='learnerattendanceentry',
            index=models.Index(fields=['school', 'register'], name='attendance__school__4ad5d9_idx'),
        ),
        migrations.AddConstraint(
            model_name='learnerattendanceentry',
            constraint=models.UniqueConstraint(fields=('school', 'register', 'learner'), name='unique_learner_attendance_entry'),
        ),
        migrations.AddIndex(
            model_name='staffattendanceentry',
            index=models.Index(fields=['school', 'teacher', 'status'], name='attendance__school__70c413_idx'),
        ),
        migrations.AddIndex(
            model_name='staffattendanceentry',
            index=models.Index(fields=['school', 'register'], name='attendance__school__14cd29_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffattendanceentry',
            constraint=models.UniqueConstraint(fields=('school', 'register', 'teacher'), name='unique_staff_attendance_entry'),
        ),
        migrations.AddIndex(
            model_name='attendancecorrection',
            index=models.Index(fields=['school', 'corrected_at'], name='attendance__school__7369cf_idx'),
        ),
        migrations.AddConstraint(
            model_name='attendancecorrection',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('learner_entry__isnull', False), ('staff_entry__isnull', True)), models.Q(('learner_entry__isnull', True), ('staff_entry__isnull', False)), _connector='OR'), name='attendance_correction_has_one_entry'),
        ),
        migrations.AddIndex(
            model_name='absencealert',
            index=models.Index(fields=['school', 'status', 'created_at'], name='attendance__school__fc4498_idx'),
        ),
        migrations.AddConstraint(
            model_name='absencealert',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('learner_entry__isnull', False), ('staff_entry__isnull', True)), models.Q(('learner_entry__isnull', True), ('staff_entry__isnull', False)), _connector='OR'), name='absence_alert_has_one_entry'),
        ),
    ]
