# Generated by Django 5.2.15 on 2026-06-13 14:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_competency_learningarea_learningoutcome_and_more'),
        ('learners', '0004_learner_membership'),
        ('tenancy', '0004_milestone_3_rls'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'Pending generation'), ('generating', 'Generating'), ('ready', 'Ready'), ('published', 'Published'), ('failed', 'Failed')], default='pending', max_length=16)),
                ('snapshot', models.JSONField()),
                ('snapshot_hash', models.CharField(max_length=64)),
                ('principal_remark', models.TextField(blank=True)),
                ('pdf', models.FileField(blank=True, upload_to='report-cards/%Y/%m/')),
                ('pdf_checksum', models.CharField(blank=True, max_length=64)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='learners.learner')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='published_report_cards', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_cards', to='tenancy.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='report_cards', to='academics.term')),
            ],
            options={
                'ordering': ['-term__start_date', 'learner__last_name'],
            },
        ),
        migrations.CreateModel(
            name='ReportGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('report', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='generation_job', to='reports.reportcard')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_generation_jobs', to='tenancy.school')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['school', 'status', 'term'], name='reports_rep_school__0a4b46_idx'),
        ),
        migrations.AddIndex(
            model_name='reportcard',
            index=models.Index(fields=['school', 'learner'], name='reports_rep_school__ae2df3_idx'),
        ),
        migrations.AddConstraint(
            model_name='reportcard',
            constraint=models.UniqueConstraint(fields=('school', 'learner', 'term'), name='unique_report_card_per_learner_term'),
        ),
        migrations.AddIndex(
            model_name='reportgenerationjob',
            index=models.Index(fields=['school', 'status', 'created_at'], name='reports_rep_school__0474a3_idx'),
        ),
    ]
