# Generated by Django 5.2.15 on 2026-06-13 17:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auditlog'),
        ('learners', '0004_learner_membership'),
        ('tenancy', '0007_milestone_6_rls'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('category', models.CharField(max_length=80)),
                ('meeting_schedule', models.CharField(blank=True, max_length=160)),
                ('is_active', models.BooleanField(default=True)),
                ('patron', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.membership')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.school')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityParticipation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(default='Member', max_length=80)),
                ('achievements', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('learner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='learners.learner')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenancy.school')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='activities.club')),
            ],
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.UniqueConstraint(fields=('school', 'name'), name='unique_school_club_name'),
        ),
        migrations.AddConstraint(
            model_name='activityparticipation',
            constraint=models.UniqueConstraint(fields=('school', 'club', 'learner'), name='unique_club_participant'),
        ),
    ]
